<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net8.0-windows</TargetFramework>
    <UseWPF>true</UseWPF>
    <Nullable>disable</Nullable>
    <LangVersion>latest</LangVersion>
    <AssemblyName>DeployToSolution</AssemblyName>
    <RootNamespace>DeployToSolution</RootNamespace>
    <ApplicationIcon />
    <SatelliteResourceLanguages>en</SatelliteResourceLanguages>
    <Version>1.0.0</Version>
    <Product>Deploy To Solution</Product>
  </PropertyGroup>

</Project>
